### ISSUE TITLE
Definition of filebeat metrics

### ISSUE THREAD

**Issue by vinothayyavoo** [sepich/beats-exporter#2]
Would like to understand the definition of each filebeat metrics. For example, in your code, it is mentioned filebeat_pipeline_*. I am using a beat exporter to send metrics to prometheus but don't have much idea as to what each metric define. 

More information here : https://elasticstack.slack.com/archives/CNEDGGJQ3/p1623426469185900?thread_ts=1623160189.152600&cid=CNEDGGJQ3

**Comment by vinothayyavoo** [comment]
@sepich

**Comment by sepich** [comment]
Sorry I do not have access to this slack.
This exporter just converts elastic metrics from `json` format to `openmetrics`, to be consumed by prometheus.
What these metrics originally mean is a question to elastic stack docs.
