### ISSUE TITLE
licence / licence file

### ISSUE THREAD

**Issue by pfulier** [sepich/beats-exporter#3]
Dear @sepich,

many thanks for this beats internal metrics exporter project - it is really nice.

I hope you are sharing it publicly  to make it available for further use.

Please would you be so kind and specify the  license type for the repo (and add the LICENSE file), so the code and sepa/beats-exporter docker image can  be used in general (eg. Apache 2/MIT)? 

Thank you very much

Peter

**Comment by sepich** [comment]
Sure, added

**Comment by pfulier** [comment]
Thank you

Kind regards,

Peter
